# .travis.yml for Product Catalog Service

language: java
jdk:
  - openjdk-21

services:
  - mysql

env:
  global:
    - SPRING_PROFILES_ACTIVE=unit
    - MYSQL_USER=test
    - MYSQL_PASSWORD=test
    - MYSQL_DB=testdb
    - MYSQL_PORT=3306

before_install:
  - echo "Setting up MySQL for tests..."
  - mysql -e 'CREATE DATABASE IF NOT EXISTS testdb;'
  - mysql -e "CREATE USER IF NOT EXISTS 'test'@'localhost' IDENTIFIED BY 'test';"
  - mysql -e "GRANT ALL PRIVILEGES ON testdb.* TO 'test'@'localhost';"
  - mysql -e "FLUSH PRIVILEGES;"

install:
  - mvn clean install -DskipTests=true -B -V

script:
  # Run unit tests only
  - make test
  # Run integration tests using TestContainers
  - make it

after_success:
  - echo "Build and tests completed successfully!"

cache:
  directories:
    - $HOME/.m2

notifications:
  email:
    recipients:
      - subhashish.sb@gmail.com
    on_success: always
    on_failure: always
